// ============================================
// 📄 1. src/types/faq.types.ts
// ============================================

export interface FAQ {
    faqId: string;        // 22자 Short UUID (예: "VQ6EAOKbQdSnFkRmVUQAAA")
    question: string;
    answer: string;
    category?: string;
    tags?: string | string[];  // Backend는 string, Frontend는 string[]로 사용 가능
    productId?: string;
    productName?: string;
    status: 'draft' | 'published';
    isAutoGenerated: boolean;
    source: 'pdf' | 'chatbot' | 'manual';
    viewCount: number;
    helpfulCount: number;
    createdAt: Date;
    updatedAt: Date;
    createdBy: string;
}

export interface FAQAutoGenerateResult {
  question: string;
  suggestedAnswer: string;
  occurrence: number;
  confidence: number;
}