from pydantic import BaseModel, Field
from typing import Optional
from datetime import datetime

class FAQBase(BaseModel):
    question: str
    answer: str
    tags: Optional[str] = None
    product_internal_id: Optional[int] = None
    faq_status: Optional[str] = None
    source: str

class FAQCreate(FAQBase):
    pass

class FAQUpdate(FAQBase):
    pass

class FAQResponse(FAQBase):
    faq_id: str  # 외부 노출용 ID만 반환
    is_autogenerated: bool
    created_by: Optional[int]
    created_at: datetime
    updated_by: Optional[int]
    updated_at: datetime
    
    class Config:
        from_attributes = True