from datetime import datetime
from sqlalchemy import Column, Integer, String, Text, Enum, Boolean, TIMESTAMP, ForeignKey, Index, BINARY, func
from sqlalchemy.ext.declarative import declarative_base
from .base import Base
import uuid

def generate_short_id() -> bytes:
    """
    BINARY(16) DB용 UUID 생성
    """
    uid = uuid.uuid4()
    encoded = uid.bytes
    return encoded

class FAQ(Base):
    __tablename__ = "tb_faq"
    
    faq_internal_id = Column(Integer, primary_key=True, autoincrement=True, comment='고유 식별자')
    faq_id = Column(BINARY(16), nullable=False, comment='FAQ ID')

    question = Column(Text, nullable=False, comment='질문')
    answer = Column(Text, nullable=False, comment='답변')
    
    company_internal_id = Column(Integer, ForeignKey("tb_company.company_internal_id", ondelete="SET NULL"), nullable=False, index=True, comment='기업 고유 식별자')
    product_internal_id = Column(Integer, ForeignKey("tb_product.product_internal_id", ondelete="SET NULL"), nullable=False, index=True, comment='제품 고유 식별자')
    
    tags = Column(String(100), comment='태그')
    
    faq_status = Column(Enum('active', 'inactive', 'candidate', 'draft'), nullable=False, default='draft', index=True, comment='상태')
    is_autogenerated = Column(Boolean, nullable=False, default=False, comment='자동 생성 여부')
    source = Column(Enum('PDF', 'Chatbot', 'Manual'), nullable=False, default='PDF', comment='출처')
    
    created_by = Column(Integer, ForeignKey("tb_admin.admin_internal_id", ondelete="SET NULL"), nullable=True, comment='생성자')
    created_at = Column(TIMESTAMP, nullable=False, server_default=func.now(), comment='생성 일시')
    updated_by = Column(Integer, ForeignKey("tb_admin.admin_internal_id", ondelete="SET NULL"), nullable=True, comment='변경자')
    updated_at = Column(TIMESTAMP, nullable=True, server_default=func.now(), onupdate=func.now(), comment='변경 일시')

    __table_args__ = (
        Index('idx_faq_search', 'question', 'answer', mysql_prefix='FULLTEXT'),
    )

    def __init__(self, **kwargs):
        if 'faq_id' not in kwargs:
            kwargs['faq_id'] = generate_short_id()
        super().__init__(**kwargs)