// ============================================
// 📄 src/lib/utils/faq.ts
// ============================================
// FAQ 관련 유틸리티 함수
// ============================================

import { FAQ } from '@/types/faq.types';

// Backend API 응답 타입
interface FAQResponse {
  faq_id: string;
  question: string;
  answer: string;
  tags?: string | null;
  product_internal_id?: number | null;
  product_id?: string | null;
  product_name?: string | null;
  category?: string | null;
  faq_status: string;
  is_autogenerated: boolean;
  source: string;
  created_by?: string | number | null;
  created_at: string;
  updated_by?: string | number | null;
  updated_at: string;
}

/**
 * Backend 응답을 Frontend FAQ 타입으로 변환
 */
export function convertFAQResponseToFAQ(response: FAQResponse): FAQ {
  // tags를 배열로 변환 (쉼표로 구분된 문자열인 경우)
  let tags: string[] = [];
  if (response.tags) {
    if (typeof response.tags === 'string') {
      // 쉼표로 구분된 문자열을 배열로 변환
      tags = response.tags.split(',').map(tag => tag.trim()).filter(tag => tag.length > 0);
    } else if (Array.isArray(response.tags)) {
      tags = response.tags;
    }
  }

  return {
    faqId: response.faq_id,
    question: response.question,
    answer: response.answer,
    tags: tags.length > 0 ? tags : undefined,
    productInternalId: response.product_internal_id || undefined,
    productId: response.product_id ||'',
    productName: response.product_name || '',
    category: response.category || undefined,
    status: response.faq_status as 'draft' | 'candidate' | 'active' | 'inactive',
    isAutoGenerated: response.is_autogenerated,
    source: response.source as 'PDF' | 'Chatbot' | 'Manual',
    createdBy: response.created_by?.toString() || 'Unknown',
    createdAt: new Date(response.created_at),
    updatedBy: response.updated_by?.toString() || 'Unknown',
    updatedAt: new Date(response.updated_at),
  };
}

/**
 * FAQ 배열 변환
 */
export function convertFAQResponseArrayToFAQArray(responses: FAQResponse[]): FAQ[] {
  return responses.map(convertFAQResponseToFAQ);
}