// ============================================
// 📄 src/lib/utils/faq.ts
// ============================================
// FAQ 관련 유틸리티 함수
// ============================================

import { FAQ } from '@/types/faq.types';

// Backend API 응답 타입
interface FAQResponse {
  faq_id: string;
  question: string;
  answer: string;
  category?: string | null;
  tags?: string | null;
  product_id?: string | null;
  product_name?: string | null;
  status: string;
  is_auto_generated: boolean;
  source: string;
  view_count: number;
  helpful_count: number;
  created_at: string;
  updated_at: string;
  created_by?: string | null;
}

/**
 * Backend 응답을 Frontend FAQ 타입으로 변환
 */
export function convertFAQResponseToFAQ(response: FAQResponse): FAQ {
  // tags를 배열로 변환 (쉼표로 구분된 문자열인 경우)
  let tags: string[] = [];
  if (response.tags) {
    if (typeof response.tags === 'string') {
      // 쉼표로 구분된 문자열을 배열로 변환
      tags = response.tags.split(',').map(tag => tag.trim()).filter(tag => tag.length > 0);
    } else if (Array.isArray(response.tags)) {
      tags = response.tags;
    }
  }

  return {
    faqId: response.faq_id,
    question: response.question,
    answer: response.answer,
    category: response.category || undefined,
    tags: tags.length > 0 ? tags : undefined,
    productId: response.product_id || undefined,
    productName: response.product_name || undefined,
    status: response.status === 'published' ? 'published' : 'draft',
    isAutoGenerated: response.is_auto_generated,
    source: response.source as 'pdf' | 'chatbot' | 'manual',
    viewCount: response.view_count,
    helpfulCount: response.helpful_count,
    createdAt: new Date(response.created_at),
    updatedAt: new Date(response.updated_at),
    createdBy: response.created_by || 'Unknown',
  };
}

/**
 * FAQ 배열 변환
 */
export function convertFAQResponseArrayToFAQArray(responses: FAQResponse[]): FAQ[] {
  return responses.map(convertFAQResponseToFAQ);
}

