// ============================================
// 📄 1. src/types/faq.types.ts
// ============================================

export interface FAQ {
    faqId: string;        // 22자 Short UUID (예: "VQ6EAOKbQdSnFkRmVUQAAA")
    question: string;
    answer: string;
    category?: string;
    productId: string;
    productName: string;
    tags?: string | string[] | null;  // Backend는 string, Frontend는 string[]로 사용 가능
    productInternalId?: number; 
    status: 'draft' | 'candidate' | 'active' | 'inactive';
    isAutoGenerated: boolean;
    source: 'PDF' | 'Chatbot' | 'Manual';
    createdBy: string;
    createdAt: Date;
    updatedBy: string;
    updatedAt: Date;
}

export interface FAQAutoGenerateResult {
  question: string;
  suggestedAnswer: string;
  occurrence: number;
  confidence: number;
}